name: backend
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  conduit_core: ^4.0.0
  conduit_password_hash: ^4.1.6
  mongo_dart: ^0.8.2

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.0.0
